OSEE-1 5316139 - PQMS
GridProtectionAlliance/openSEE pull request #51
Opened 2024-02-29 21:03 UTC by prestoncraw

2024-03-01 16:04 UTC, clackner-gpa requested changes

2024-03-01 16:04 UTC, clackner-gpa commented on src/OpenSEE/Scripts/TSX/jQueryUI Widgets/Common.tsx
> +    }, [refWindow.current]);
Didn't this whole file get removed? I don't think we are suing this anywhere anymore - the widgets should all be in Drawers

2024-03-01 16:22 UTC, prestoncraw commented on src/OpenSEE/Model/D3Series.cs
> +        public int Axis;
Yes we can it is removed from all the interfaces in typescript, i will remove that

2024-03-11 15:16 UTC, clackner-gpa approved these changes

2024-03-11 15:17 UTC, merged